'use strict';

let currencies = [
    { currency: 'AFN', display: 'Afghan Afghani' },
    { currency: 'ALL', display: 'Albanian Lek' },
    { currency: 'DZD', display: 'Algerian Dinar' },
    { currency: 'AOA', display: 'Angolan Kwanza' },
    { currency: 'ARS', display: 'Argentine Peso' },
    { currency: 'AMD', display: 'Armenian Dram' },
    { currency: 'AWG', display: 'Aruban Florin' },
    { currency: 'AUD', display: 'Australian Dollar' },
    { currency: 'AZN', display: 'Azerbaijani Manat' },
    { currency: 'BSD', display: 'Bahamian Dollar' },
    { currency: 'BHD', display: 'Bahraini Dinar' },
    { currency: 'BDT', display: 'Bangladeshi Taka' },
    { currency: 'BBD', display: 'Barbadian Dollar' },
    { currency: 'BYR', display: 'Belarusian Ruble' },
    { currency: 'BZD', display: 'Belize Dollar' },
    { currency: 'BMD', display: 'Bermudan Dollar' },
    { currency: 'BTN', display: 'Bhutanese Ngultrum' },
    { currency: 'BTC', display: 'Bitcoin' },
    { currency: 'BOB', display: 'Bolivian Boliviano' },
    {
        currency: 'BAM',
        display: 'Bosnia-Herzegovina Convertible Mark'
    },
    { currency: 'BWP', display: 'Botswanan Pula' },
    { currency: 'BRL', display: 'Brazilian Real' },
    { currency: 'GBP', display: 'British Pound Sterling' },
    { currency: 'BND', display: 'Brunei Dollar' },
    { currency: 'BGN', display: 'Bulgarian Lev' },
    { currency: 'BIF', display: 'Burundian Franc' },
    { currency: 'XOF', display: 'CFA Franc BCEAO' },
    { currency: 'XAF', display: 'CFA Franc BEAC' },
    { currency: 'XPF', display: 'CFP Franc' },
    { currency: 'KHR', display: 'Cambodian Riel' },
    { currency: 'CAD', display: 'Canadian Dollar' },
    { currency: 'CVE', display: 'Cape Verdean Escudo' },
    { currency: 'KYD', display: 'Cayman Islands Dollar' },
    { currency: 'CLP', display: 'Chilean Peso' },
    { currency: 'CLF', display: 'Chilean Unit of Account (UF)' },
    { currency: 'CNY', display: 'Chinese Yuan' },
    { currency: 'COP', display: 'Colombian Peso' },
    { currency: 'KMF', display: 'Comorian Franc' },
    { currency: 'CDF', display: 'Congolese Franc' },
    { currency: 'CRC', display: 'Costa Rican Colón' },
    { currency: 'HRK', display: 'Croatian Kuna' },
    { currency: 'CUC', display: 'Cuban Convertible Peso' },
    { currency: 'CUP', display: 'Cuban Peso' },
    { currency: 'CZK', display: 'Czech Republic Koruna' },
    { currency: 'DKK', display: 'Danish Krone' },
    { currency: 'DJF', display: 'Djiboutian Franc' },
    { currency: 'DOP', display: 'Dominican Peso' },
    { currency: 'XCD', display: 'East Caribbean Dollar' },
    { currency: 'EGP', display: 'Egyptian Pound' },
    { currency: 'ERN', display: 'Eritrean Nakfa' },
    { currency: 'EEK', display: 'Estonian Kroon' },
    { currency: 'ETB', display: 'Ethiopian Birr' },
    { currency: 'EUR', display: 'Euro' },
    { currency: 'FKP', display: 'Falkland Islands Pound' },
    { currency: 'FJD', display: 'Fijian Dollar' },
    { currency: 'GMD', display: 'Gambian Dalasi' },
    { currency: 'GEL', display: 'Georgian Lari' },
    { currency: 'GHS', display: 'Ghanaian Cedi' },
    { currency: 'GIP', display: 'Gibraltar Pound' },
    { currency: 'XAU', display: 'Gold (troy ounce)' },
    { currency: 'GTQ', display: 'Guatemalan Quetzal' },
    { currency: 'GGP', display: 'Guernsey Pound' },
    { currency: 'GNF', display: 'Guinean Franc' },
    { currency: 'GYD', display: 'Guyanaese Dollar' },
    { currency: 'HTG', display: 'Haitian Gourde' },
    { currency: 'HNL', display: 'Honduran Lempira' },
    { currency: 'HKD', display: 'Hong Kong Dollar' },
    { currency: 'HUF', display: 'Hungarian Forint' },
    { currency: 'ISK', display: 'Icelandic Króna' },
    { currency: 'INR', display: 'Indian Rupee' },
    { currency: 'IDR', display: 'Indonesian Rupiah' },
    { currency: 'IRR', display: 'Iranian Rial' },
    { currency: 'IQD', display: 'Iraqi Dinar' },
    { currency: 'ILS', display: 'Israeli New Sheqel' },
    { currency: 'JMD', display: 'Jamaican Dollar' },
    { currency: 'JPY', display: 'Japanese Yen' },
    { currency: 'JEP', display: 'Jersey Pound' },
    { currency: 'JOD', display: 'Jordanian Dinar' },
    { currency: 'KZT', display: 'Kazakhstani Tenge' },
    { currency: 'KES', display: 'Kenyan Shilling' },
    { currency: 'KWD', display: 'Kuwaiti Dinar' },
    { currency: 'KGS', display: 'Kyrgystani Som' },
    { currency: 'LAK', display: 'Laotian Kip' },
    { currency: 'LVL', display: 'Latvian Lats' },
    { currency: 'LBP', display: 'Lebanese Pound' },
    { currency: 'LSL', display: 'Lesotho Loti' },
    { currency: 'LRD', display: 'Liberian Dollar' },
    { currency: 'LYD', display: 'Libyan Dinar' },
    { currency: 'LTL', display: 'Lithuanian Litas' },
    { currency: 'MOP', display: 'Macanese Pataca' },
    { currency: 'MKD', display: 'Macedonian Denar' },
    { currency: 'MGA', display: 'Malagasy Ariary' },
    { currency: 'MWK', display: 'Malawian Kwacha' },
    { currency: 'MYR', display: 'Malaysian Ringgit' },
    { currency: 'MVR', display: 'Maldivian Rufiyaa' },
    { currency: 'IMP', display: 'Manx pound' },
    { currency: 'MRO', display: 'Mauritanian Ouguiya' },
    { currency: 'MUR', display: 'Mauritian Rupee' },
    { currency: 'MXN', display: 'Mexican Peso' },
    { currency: 'MDL', display: 'Moldovan Leu' },
    { currency: 'MNT', display: 'Mongolian Tugrik' },
    { currency: 'MAD', display: 'Moroccan Dirham' },
    { currency: 'MZN', display: 'Mozambican Metical' },
    { currency: 'MMK', display: 'Myanma Kyat' },
    { currency: 'NAD', display: 'Namibian Dollar' },
    { currency: 'NPR', display: 'Nepalese Rupee' },
    { currency: 'ANG', display: 'Netherlands Antillean Guilder' },
    { currency: 'TWD', display: 'New Taiwan Dollar' },
    { currency: 'NZD', display: 'New Zealand Dollar' },
    { currency: 'NIO', display: 'Nicaraguan Córdoba' },
    { currency: 'NGN', display: 'Nigerian Naira' },
    { currency: 'KPW', display: 'North Korean Won' },
    { currency: 'NOK', display: 'Norwegian Krone' },
    { currency: 'OMR', display: 'Omani Rial' },
    { currency: 'PKR', display: 'Pakistani Rupee' },
    { currency: 'PAB', display: 'Panamanian Balboa' },
    { currency: 'PGK', display: 'Papua New Guinean Kina' },
    { currency: 'PYG', display: 'Paraguayan Guarani' },
    { currency: 'PEN', display: 'Peruvian Nuevo Sol' },
    { currency: 'PHP', display: 'Philippine Peso' },
    { currency: 'PLN', display: 'Polish Zloty' },
    { currency: 'QAR', display: 'Qatari Rial' },
    { currency: 'RON', display: 'Romanian Leu' },
    { currency: 'RUB', display: 'Russian Ruble' },
    { currency: 'RWF', display: 'Rwandan Franc' },
    { currency: 'SHP', display: 'Saint Helena Pound' },
    { currency: 'SVC', display: 'Salvadoran Colón' },
    { currency: 'WST', display: 'Samoan Tala' },
    { currency: 'SAR', display: 'Saudi Riyal' },
    { currency: 'RSD', display: 'Serbian Dinar' },
    { currency: 'SCR', display: 'Seychellois Rupee' },
    { currency: 'SLL', display: 'Sierra Leonean Leone' },
    { currency: 'XAG', display: 'Silver (troy ounce)' },
    { currency: 'SGD', display: 'Singapore Dollar' },
    { currency: 'SBD', display: 'Solomon Islands Dollar' },
    { currency: 'SOS', display: 'Somali Shilling' },
    { currency: 'ZAR', display: 'South African Rand' },
    { currency: 'KRW', display: 'South Korean Won' },
    { currency: 'XDR', display: 'Special Drawing Rights' },
    { currency: 'LKR', display: 'Sri Lankan Rupee' },
    { currency: 'SDG', display: 'Sudanese Pound' },
    { currency: 'SRD', display: 'Surinamese Dollar' },
    { currency: 'SZL', display: 'Swazi Lilangeni' },
    { currency: 'SEK', display: 'Swedish Krona' },
    { currency: 'CHF', display: 'Swiss Franc' },
    { currency: 'SYP', display: 'Syrian Pound' },
    { currency: 'STD', display: 'São Tomé and Príncipe Dobra' },
    { currency: 'TJS', display: 'Tajikistani Somoni' },
    { currency: 'TZS', display: 'Tanzanian Shilling' },
    { currency: 'THB', display: 'Thai Baht' },
    { currency: 'TOP', display: 'Tongan Paʻanga' },
    { currency: 'TTD', display: 'Trinidad and Tobago Dollar' },
    { currency: 'TND', display: 'Tunisian Dinar' },
    { currency: 'TRY', display: 'Turkish Lira' },
    { currency: 'TMT', display: 'Turkmenistani Manat' },
    { currency: 'UGX', display: 'Ugandan Shilling' },
    { currency: 'UAH', display: 'Ukrainian Hryvnia' },
    { currency: 'AED', display: 'United Arab Emirates Dirham' },
    { currency: 'UYU', display: 'Uruguayan Peso' },
    { currency: 'UZS', display: 'Uzbekistan Som' },
    { currency: 'VUV', display: 'Vanuatu Vatu' },
    { currency: 'VEF', display: 'Venezuelan Bolívar Fuerte' },
    { currency: 'VND', display: 'Vietnamese Dong' },
    { currency: 'YER', display: 'Yemeni Rial' },
    { currency: 'ZMW', display: 'Zambian Kwacha' },
    { currency: 'ZMK', display: 'Zambian Kwacha (pre-2013)' },
    { currency: 'ZWL', display: 'Zimbabwean Dollar' }]
export = currencies;



